### ISSUE TITLE
Cannot edit a grid cell of an enum column

### ISSUE THREAD

**Issue by ryancwalsh** [dbeaver/dbeaver#21167]
### Description

In DBeaver, when I try to edit a grid cell of an enum column, I get:

```
Reason:
SQL Error [42804]: ERROR: column "flag" is of type "Flag" but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 33
```

My Postgres migration (generated by Prisma) said:
`CREATE TYPE "Flag" AS ENUM ('BANNED', 'FAVORITED');`

So I've tried using 'BANNED' or BANNED in the cell, but they both throw errors. I've also tried saving as 1 in case enums get converted to integers.

https://github.com/dbeaver/dbeaver/issues/72 might be related but isn't exactly what I'm talking about. In my case, I don't need to edit the column definition. I'm trying to edit a cell value in an existing row.

### DBeaver Version

community 23.2.0

### Operating System

Win 10

### Database and driver

Postgres 15
