### ISSUE TITLE
Dbeaver can't connect Postgresq hosted on Docker

### ISSUE THREAD

**Issue by KelvinxG** [dbeaver/dbeaver#34573]
### Description

Docker-compose.yml

```yml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
```

error messages : FATAL: password authentication failed for user "postgres" 

I turned off the firewall.

i tried everything, i googled , i used chatgpt.

I don't know what to do with this.

### DBeaver Version

24.1.1

### Operating System

Windows 10
