### ISSUE TITLE
pg database passwords use special characters such as! & Unable to connect; I can connect with navcat;

### ISSUE THREAD

**Issue by TomYule** [dbeaver/dbeaver#34838]
### Description

pg database passwords use special characters such as! & Unable to connect; I can connect with navcat;

### DBeaver Version

版本: 23.3.5.202402181738

### Operating System

macos monterey 12.7.5

### Database and driver

Example:
1. Database name and version: PostgreSQL 13.0
2. Driver name and version: PostgreSQL JDBC Driver 42.2.25

### Steps to reproduce

![图片](https://github.com/user-attachments/assets/756aed07-bb93-4cfd-a688-71e6d0b14b50)

### Additional context

use docker compose create db
```
  postgres:
    image: postgres:13
    container_name: anhui-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kefuzhuli_bb
      POSTGRES_USER: pgu_kefuzhuli
      POSTGRES_PASSWORD: IbPS18!&4cm
    volumes:
      - pg-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M


```

FATAL: password authentication failed for user "pgu_kefuzhuli"
