### ISSUE TITLE
Setting a boolean value in the inline data editor fails with binding not supported (Oracle DB)

### ISSUE THREAD

**Issue by Piiit** [dbeaver/dbeaver#36022]
### Description

I have the following table in an Oracle:
```
CREATE TABLE USERS (
	ID NUMBER(38,0),
	EMAIL VARCHAR2(4000),
	PASSWORD VARCHAR2(4000),
	ENABLED BOOLEAN DEFAULT 0
);
```

I can insert/update a boolean for ENABLED easily when using the SQL text editor:
```
insert into users (email, password, enabled) values ('a@test.com', 'asdf', false);
update users set enabled = true where email = 'a@test.com';
```

The same fails when I want to insert or update such a row with the data editor:
<img width="630" alt="image" src="https://github.com/user-attachments/assets/59b6b84c-5890-4c7e-bb07-7d5bf44dba94">

It seems that the column is not recognized as boolean at all, since normally (Postgres) I can just click a checkbox to change boolean values.

### DBeaver Version

24.2.2.202410061621 Community Edition

### Operating System

macOS 15 Sequoia

### Database and driver

Database name and version taken from Docker Hub: `image: gvenzl/oracle-free:23.5-slim-faststart`

DBeaver DB driver: 
<img width="435" alt="image" src="https://github.com/user-attachments/assets/ae66609b-9c92-4b36-b0ba-ec7ff806b35e">

### Steps to reproduce

1. Start the database with `docker compose up` (Docker compose file below)
```
services:

  oracle:
    image: gvenzl/oracle-free:23.5-slim-faststart
    environment:
      ORACLE_DATABASE: app
      ORACLE_PASSWORD: password
      APP_USER: root
      APP_USER_PASSWORD: password
    ports:
      - "1521:1521"
```

2. Connect to it with DBeaver: connection string = `jdbc:oracle:thin:@//localhost:1521/app` (I kept all default settings for other connection parameters) 
<img width="671" alt="image" src="https://github.com/user-attachments/assets/b959723f-bac1-4fa0-8ec0-85f90f36b0ac">

3. create table 
```
CREATE TABLE USERS (
	ID NUMBER(38,0),
	EMAIL VARCHAR2(4000),
	PASSWORD VARCHAR2(4000),
	ENABLED BOOLEAN DEFAULT 0
);
```

4. Go to the data editor and try to insert a row

It fails saying:

```
Error synchronizing data with database

Reason:
Parameter [ENABLED] value [true] binding not supported
```
