### ISSUE TITLE
Clickhouse JDBC 0.8.x not working

### ISSUE THREAD

**Issue by pythoneer** [dbeaver/dbeaver#37671]
### Description

After upgrading to the 0.8.x line of the JDBC driver from ClickHouse i am unable to connect to my local (docker) instance and the one running on ClickHouse Cloud. I am presented with this error

![Image](https://github.com/user-attachments/assets/b0456c85-cad0-446c-b651-f6b49d2fbb36)

I figured that the value (`false` in the screenshot) comes from the connection settings -> driver properties -> `use_time_zone`. 

![Image](https://github.com/user-attachments/assets/89747449-e623-48a7-bfa6-44701538f316)

Changing it to something else (`true`, empty, `utc`) does not seem to have an effect. Almost looks like it complains that this key even exists – but i can't remove it. 7 and 6 series drivers works fine with this property (`false`) as default. I did not change it in the first place, just upgraded the version from 6 to 8 and also tried to make the connection from scratch with no effect. 

### DBeaver Version

Community Edition 25.0.0.202503101833

### Operating System

Arch Linux (6.13.8-arch1-1)

### Database and driver

Clickhouse 25.2
Clickhouse JDBC 0.8.2 (0.8.1, 0.8.0)

### Steps to reproduce

create a file `docker-compose.yml` with this content

```yml
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.2-alpine
    container_name: clickhouse-driver-test
    ports:
      - "18123:8123"
      - "19000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=changeme
    volumes:
      - ./data:/var/lib/clickhouse
```

run `docker compose up`

Make a new connection in dbeaver with 
localhost:18123 
db: default 
user: default 
password: changeme

And in driver settings -> libraries change between e.g. v0.6 und v0.8

![Image](https://github.com/user-attachments/assets/03ad49f8-0814-4d21-943b-07e4c7fb0793)

Test connection give the error message from above on 0.8.x line of drivers but works on 0.6.x and 0.7.x
