### ISSUE TITLE
HostSNI Server Name Indication

### ISSUE THREAD

**Issue by truesilver92** [dbeaver/dbeaver#7758]
#### System information: 
- Manjaro Linux release 18.1.5 (rolling release updated within the week)
- DBeaver version 6.3.3.202001202110

#### Connection specification:
- Trying to connect to postgres version 12 using the PostgreSQL JDBC
  Driver

#### Describe your question:
Is it possible to set DBeaver or the connection driver to use HostSNI
(server name indication) for an ssl connection? I am trying to use
traefik (traefik.io) to do TCP routing of multiple postgres databases listening on
the same port. I am doing this so that my coworkers can easily connect
to a specific project's database on my machine. I want to be able to
tell them the web page is at `[project].[machine name].[rest of intranet FQDN]`
(working now) and the database for that project is at
the same url with the default port for that database engine.

**Comment by serge-rider** [comment]
https://stackoverflow.com/questions/59264410/how-to-connect-to-traefik-tcp-services-with-tls-configuration-enabled

**Comment by truesilver92** [comment]
Not that HostSNI wouldn't be a nice feature in dbeaver, but @serge-rider 's link shows that my specific use case will probably not work even if dbeaver added support for it.

**Comment by truesilver92** [comment]
Actually I take that back some. Postgres could run without TLS while traefik does the TLS proxying.

**Comment by sreeram-venkitesh** [comment]
SNI routing for postgres with STARTTLS has been added to Traefik in [this](https://github.com/traefik/traefik/pull/9377) PR. Now Treafik will listen to the initial bytes sent by postgres and if its going to initiate a TLS handshake (Note that postgres TLS requests are created as non-TLS first and then upgraded to TLS requests), Treafik will handle the handshake and then is able to receive the TLS headers from postgres, which contains the SNI information that it needs to route the request properly. This means that you can use HostSNI("example.com") along with tls to expose postgres databases under different subdomains.

As of writing this answer, I was able to get this working with the v3.0.0-beta2 image ([Reference](https://github.com/traefik/traefik-helm-chart/issues/757#issuecomment-1366135192))

**Comment by humpalu** [comment]
@sreeram-venkitesh I have exactly the same scenario. Could you please share your config with me? It could be a huge help! Im super stucked to setup the multi domain postgres with compose on one machine.

**Comment by sreeram-venkitesh** [comment]
@tothger This was the config for the IngressRouteTCP resource I had used. This assumes that you are running on the appropriate version of Traefik (> v3.0.0-beta2)

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: <%= addon_name %>-ingressroutetcp

spec:
  entryPoints:
    - <%= entrypoint %> #postgres or redis, configured when you setup Traefik
  routes:
  - match: HostSNI(`<%= addon_name %>.<%= domain_name %>`)
    services:
    - name: <%= addon_name %>
      port: <%= port %> #based on postgres/redis
  tls:
    secretName: tls-certificate-secret #for your domain_name - configured in cluster with cert-manager
```
