### ISSUE TITLE
Neo4j: not able to connect 

### ISSUE THREAD

**Issue by pelletier197** [dbeaver/dbeaver#8241]
Hello,

When trying to connect to a local instance of Neo4j running in docker, I get an unexpected error from DBeaver: 

![image](https://user-images.githubusercontent.com/24528884/77235876-f8fc4880-6b8f-11ea-95c6-4a420e1892f3.png)

The error is `Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database`

Here is the simple docker-compose file I used to launch the Neo4j instance: 

```yaml
version: "3.7"

services:
  neo4j:
    image: neo4j:4.0.2
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/root
    ports:
      - 7687:7687
      - 7474:7474
      - 7473:7473
```

If i use the Neo4j browser based navigator, I am able to connect using the credentials provided in the docker-compose file. 

I tried connecting to all the available ports without any success.

Thank you for your help!
